### PR TITLE
Small codestyle fixes to make code more debuggable

### PR DESCRIPTION
**Pull request by politsin**

### CODE REVIEW

**Comment by mr-troll** [comment]
Why did you replace all tabs identation to spaces? How it will be more debuggable?

**Comment by yourivw** [comment]
I agree with @mr-troll that this does not seem to make code more debuggable.

**Comment by politsin** [comment]
1) Here is the place of "make more debuggable" https://github.com/yourivw/LEClient/pull/63/commits/b2c955bda2b761340c889d1a6cdc51cade7e59a3#diff-931d8adf2119d88bde2656344a3685e1R156
2) `tabs identation to spaces` - is auto codestyle from IDE

**Comment by yourivw** [comment]
I am wondering whether this actually makes it more debuggable, but I'm not merging a PR changing all the tab indentations for the simple reason that it changes a lot of lines, which will break previous changes since this is already an older PR.

**Comment by mr-troll** [comment]
@politsin , If there is some addition to 156 line ($error_post), then please do PL without breaking indentation. 
"tabs identation" - is subject of preference of project, not linked to any IDE, in most cases tabs are more convenient, than fixed lenght spaces.

**Pull request closed without merging**
