### PR TITLE
[BUG] Removed undefined variable

### PR DESCRIPTION
**Pull request by fendrychl**
Related issue: #47

### CODE REVIEW

**Comment by fendrychl** [comment]
Related issue: #47

**Comment by marcolumia** [comment]
Can you please merge this fix. I created a pull request for the same issue and realized it already was a pending pull request.

**Comment by marcolumia** [comment]
@yourivw can we merge this pull request. It solves a very simple bug in the master branch that prevents the package from being usable.

**Comment by michabbb** [comment]
@yourivw please, because today i ran into the same issue 😖

**Comment by pascalschoeni** [comment]
@yourivw Please, I also created a pull request

**Pull request merged**
