### PR TITLE
fix Invalid response, header: HTTP/2 200 

### PR DESCRIPTION
**Pull request by a3dho3yn**
We encountered an error while renewing certificates: `Invalid response, header: HTTP/2 200 `, which shows a breaking change in Let's Encrypt API. It's more robust to check status code directly instead of looking for "200 OK" or something in header.

### CODE REVIEW

**Comment by a3dho3yn** [comment]
@yourivw would you please review this? It is critical (client doesn't work :( )

**Comment by sagarspatil** [comment]
@a3dho3yn Your git page does not have contact info, how do I get in touch with you? :)

**Comment by a3dho3yn** [comment]
Any body reads me?

**Comment by yourivw** [comment]
Unfortunately I was not able to go online and fix this earlier. Now fixed in release [1.1.10](https://github.com/yourivw/LEClient/releases/tag/1.1.10). Thanks for the fix!

**Pull request merged**
