### PR TITLE
Fix check dns challenge

### PR DESCRIPTION
**Pull request by qem19**
Fix this issue https://github.com/yourivw/LEClient/issues/109

### CODE REVIEW

**Comment by bilogic** [comment]
This hasn't been committed correct?

**Comment by qem19** [comment]
It was correct, but i've done fork already and this fix is working.

**Comment by bilogic** [comment]
I know, I'm just wondering how to get it without having to write it myself haha

**Comment by qem19** [comment]
)) Well, you can use this fork https://github.com/umbrellio/LEClient. We change nothing except fix this bug.

**Comment by bilogic** [comment]
Ah ok.. i was clicking on the deleted branch and I thought the repo was no more.
Do you plan to release on packagist? This repo looks abandoned.

**Pull request closed without merging**
